### ISSUE TITLE
Integration into Nemo?

### ISSUE THREAD

**Issue by EuKV** [linuxmint/warpinator#95] opened 2021-07-09 19:24 UTC
Hi, are there plans to integrate Warpinator into Nemo?
I mean my first natural willing was to send files with right click of the mouse on them, choosing Warpinator from Nemo context menu and then selecting the computer where I want to send files to. Is it hard to implement?
I'll repeat myself but it's really "must be" from my point of view.
Thanks!

**Comment by mtwebster** [comment] 2021-07-09 19:27
duplicate of https://github.com/linuxmint/warpinator/issues/92

It's a good suggestion, something we're looking at currently.

**Closed** 2021-07-09 19:27 UTC
