### ISSUE TITLE
the app cannot find the computers on the network anymore in v1.0.0

### ISSUE THREAD

**Issue by jprando** [linuxmint/warpinator#22] opened 2020-04-21 01:41 UTC
when i used version 0.0.1 i was able to find the computers on the network and perform file transfers successfully.

I decided to update to the new version 1.0.0, in addition to the new icon (very cool) do not find the computers on the network.

- both computers are on the same network!
- both computers use Linux Mint 19.3
- the firewall is disabled in both computers
- Group Code in preferences both are equals
- i exec rm -rf $HOME/.config/warpinator

this case happened to someone else?

I am aware that the warpinator is not a finished product.
I'm testing it and I would like to report that it stopped working ...

is there any information i can provide to help solve the problem?

**Comment by mtwebster** [comment] 2020-04-21 02:07
Thanks,  I've seen this a couple of times but I have pinned it down yet (and I agree it's recent) - I need to go and figure out where I broke it.

**Comment by jprando** [comment] 2020-04-21 03:19
im try here and ...

even this works
https://github.com/linuxmint/warpinator/commit/9826e43cee0a8965bbf975da8f1d8418d8a67776

from that it doesn't work anymore
https://github.com/linuxmint/warpinator/commit/e228bcc10fc46e4c5316ed0fbdf38dfc99cd6ec8

**Comment by slowscript** [comment] 2020-04-22 19:37
> from that it doesn't work anymore
e228bcc

That's my PR. I'm however unable to reproduce the issue. I've tried multiple computers and distros (Mint, Debian, Manjaro...) and all find each other. Could you please provide some more information? Are you sure you are running the same version on both computers? Does it say something in the console? What do you see when you run `avahi-browse -at` with Warpinator running on both computers? Thanks.

**Comment by mtwebster** [comment] 2020-04-23 01:59
I'm not sure it's that commit, at least for me.

I have 3 computers I'm testing this with.

One machine has been refusing to connect to other machines reliably (though they never fail to find *it*).  I've got a fresh install on another parition, same behavior.

I just moved the 2 'problem-free' machines to use one access point on my network, the problem machine on the other (same network, subnet ,etc..) and now everything works fine between all computers.

I think if I go back to the commit prior to adding the encryption/certificate exchange, this stops happening.  But I have trouble pinning the blame solely on that (perhaps I'm trying to shove too much data into the 'parameters' of the ServiceInfo) since this doesn't happen on every machine.

The problem machine is actually getting a discovery notification, but when it tries to retrieve the ServiceInfo, it times out (even if I set the timeout to 20s).  The info is there though:
```
+ wlp4s0 IPv4 p51-20                                        _warpinator._tcp     local
+ wlp4s0 IPv4 mike-lm19-samsung                             _warpinator._tcp     local
+ wlp4s0 IPv4 mike-at3                                      _warpinator._tcp     local
+     lo IPv4 p51-20                                        _warpinator._tcp     local
```
If I run with -r I can see all the service info, including the parameter data for all 3 machines.

Any thoughts?

**Comment by slowscript** [comment] 2020-04-23 14:03
Yes, it could be that parameters are too big. I've read somewhere that the Txt record shouldn't be over 400 bytes (which it is) and that it can sometimes be truncated. This can be easily verified by running avahi-browse with -r (as you've said).
The only problem I've had was when I tried to run it with zeroconf 0.25 from pip (which is not backwards compatible) but this is likely unrelated because it doesn't explain why the issue can be fixed by using a different access point.
Again, I cannot reproduce this issue (version 1.0.0, 2 different computers, 1 VM) so I'm not sure how to be helpful here. I just noticed that my commit was mentioned and wanted to figure out what was wrong with it. I'll wait for OP to respond. I think his issue is something else if he identified that commit as the source of the problem.

**Comment by mtwebster** [comment] 2020-04-23 16:48
That's what I was worried about - I had trouble finding a definitive max size.

For kicks, I tried using a 1024 bit key size, and the problem went away.  I'm considering, at least for the time being, switching to that, and generating a new key every time warp starts.

I'm dragging my feet on not abusing the parameters this way, because I'd have to transfer this some other way using udp.

**Comment by jprando** [comment] 2020-04-23 18:15
prints...

machine 01 - IP 192.168.0.170 (DHCP dynamic)

version 0.0.1 working here
![machine01 prando warpinator v001 001](https://user-images.githubusercontent.com/4616847/80134200-c53c8600-8574-11ea-9846-752c4fc6e2e4.png)

version 1.0.0 dont working here
![machine01 prando warpinator v100 002](https://user-images.githubusercontent.com/4616847/80134217-cd94c100-8574-11ea-81b7-10a3ad393db4.png)

machine 02 - IP 192.168.0.4 (DHCP Fixed)
version 1.0.0 
![machine02 prando warpinator v100 001](https://user-images.githubusercontent.com/4616847/80134249-dbe2dd00-8574-11ea-8c95-5c1ebecbf44d.png)
version 1.0.0 dont working here
![machine02 prando warpinator v100 002](https://user-images.githubusercontent.com/4616847/80134257-e0a79100-8574-11ea-98e9-50183218201a.png)

_if there is anything i can do to provide more information, just let me know!_

**Comment by mtwebster** [comment] 2020-04-23 21:04
Can neither computer see the other? Does it sometimes work?

Can you give something a try:

edit `/usr/libexec/warpinator/auth.py` as root, find this line:

https://github.com/linuxmint/warpinator/blob/master/src/auth.py#L121

and change that 2048 to 1024, save it.  Then, go into `~/.config/warpinator/remotes` and remove all the files there.  Do this to all computers, then start warp on them.

If you're building yourself, just edit the source auth.py if you want and re-build - either way doesn't matter.  Just make sure to remove those files.

Thanks

**Comment by jprando** [comment] 2020-04-23 23:29
> Can neither computer see the other? Does it sometimes work?
> 
> Can you give something a try:
> 
> edit `/usr/libexec/warpinator/auth.py` as root, find this line:
> 
> https://github.com/linuxmint/warpinator/blob/master/src/auth.py#L121
> 
> and change that 2048 to 1024, save it. Then, go into `~/.config/warpinator/remotes` and remove all the files there. Do this to all computers, then start warp on them.
> 
> If you're building yourself, just edit the source auth.py if you want and re-build - either way doesn't matter. Just make sure to remove those files.
> 
> Thanks

- I made the change
- deleted the `/usr/libexec/warpinator` and `builddir` folder
- recompiled
- deleted the `~/.config/warpinator` folder
- ran the warpinator app

it didn't work here

I noticed that the two machines have the same name
I changed the name of one, I repeated the process

it didn't work here

**Comment by mtwebster** [comment] 2020-04-23 23:33
Do you run warpinator from a terminal? No errors there?

**Comment by jprando** [comment] 2020-04-23 23:34
yep, yep

**Comment by jprando** [comment] 2020-04-23 23:35
I will try to connect the two computers by cell phone (access point mobile)

**Comment by jprando** [comment] 2020-04-23 23:47
by mobile (hotspot)

last commit didn't work
master

this worked
9826e43

**Comment by slowscript** [comment] 2020-04-24 08:31
Thanks for the screenshots. I think I see 3 problems. Correct me if I got something wrong.
1) Machine 1 sees machine 2, but in the second picture (not working, version 1.0.0) it appears that machine 2 is still running the old version which is incompatible with the new one (old format of service name - starting with "warpinator" instead of hostname). 
2) Machine 2 doesn't see machine 1 at all. No idea why. But in both of its screenshots it seems that it's running the new version. I'm confused now.
3) Both machines appear to be named the same. This made me aware of a regression in my commit. Removing the IP address from the service name removes a bit of uniqueness, so when Warpinator sees a service with the same name, it thinks that's the local machine and ignores it. You've said you changed the name later, so that's not the cause of your issue. I will still try to fix this though.

The Txt records look normal and I don't see any truncation. All I can advise is to double-check the version you are running on both machines. Maybe also restart Warpinator once more to make sure the DNS-SD record gets updated. All entries in avahi-browse -at should be in the same format after switching the version.

**Comment by jprando** [comment] 2020-04-24 14:02
ok i will try here.

about _appears that machine 2 is still running the old version_

- machine 01 - picture 001 - version 0.0.1 ( it do work )
- machine 01 - picture 002 - version **1.0.0**
- machine 02 - picture 001 - version 0.0.1 ( it do work )
- machine 02 - picture 002 - version **1.0.0**

I will try to extract more information for you...

**Comment by jprando** [comment] 2020-04-24 14:07
about item 3:

🤔 suggestion: use hash
_warpinator + hash( ip + hostname +  anything )_

result: warpinator_35b96a650c2fbb93d23dd81116b561b8

no matter what size or amount of information you use to generate the hash, it will always be a fixed size 😉

**Comment by jprando** [comment] 2020-04-24 15:12
my network topology

![mynetwork](https://user-images.githubusercontent.com/4616847/80228010-e2c92880-8624-11ea-95fa-11a23837c857.png)

**Comment by jprando** [comment] 2020-04-24 23:09
I have news ...

- changing the name of computers
- changing the wifi router
- returned to the wifi router from before

now wapinator v1.0.0 is working

![warpinator v100 working](https://user-images.githubusercontent.com/4616847/80263488-2a70a400-8667-11ea-96ce-9c1dd85b5f2b.png)

I put the same name again, and it stopped working!
changing, again, the names of the computers to be different returned to work

**Comment by jprando** [comment] 2020-04-25 01:14
I returned the change from file `/src/auth.py`
from value 1024 to value 2048
in `key_size` and it still works

**Comment by slowscript** [comment] 2020-04-25 09:01
So it's just problem 3. I will look at it and make a PR when I have time to do so (hopefully today).

**Comment by slowscript** [comment] 2020-04-28 16:15
Hi, sorry for the delay. Now that I've got time to look at this, it seems that it won't be as simple as I thought. I tried implementing Android's NSD's approach: appending "(2)", "(3)" etc. to the hostname ("_2", "_3" in my case). That broke the authentication for some reason. It finds the other machine but then this happens (even if I delete the config folder):
`Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.`
You can check it out [here](https://github.com/slowscript/warp/commit/49f584c704139a847ab94da342bd4378395a1a1f). One issue could be that the certificates are stored with the hostname as file name, so maybe it gets incorrectly overwritten? If that's the case, I don't know how it's possible it worked before. I don't understand this cryptography stuff, so I've given up on this path.
The easiest solution would be to just tell users that they shouldn't use the same hostname on more than one machine since that causes issues with other programs anyway. Another could be to return to having the IP in the name. I don't know how that worked but maybe it could work again...
What do you think?

**Closed** 2020-05-02 02:47 UTC
Labels: bug
